# Generated by Django 5.2.1 on 2025-06-28 15:41

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-profile-photo_e0dzna', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile_pictures'),
        ),
    ]
