# Generated by Django 5.2.1 on 2025-05-27 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalchat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalchatmessage',
            name='user_online',
            field=models.ManyToManyField(blank=True, related_name='online_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
