# Generated by Django 5.2.1 on 2025-05-27 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalchat', '0002_globalchatmessage_user_online'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalchatmessage',
            name='user_online',
        ),
        migrations.CreateModel(
            name='GlobalChatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_online', models.ManyToManyField(blank=True, related_name='global_online_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
