# Generated by Django 5.2.1 on 2025-05-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
