# Generated by Django 5.2.1 on 2025-05-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0002_alter_noticeboard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
