# Generated by Django 5.2.1 on 2025-06-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0004_noticeboard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notices/'),
        ),
    ]
