# Generated by Django 5.2.1 on 2025-06-28 10:48

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0005_alter_noticeboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='notices/'),
        ),
    ]
