# Generated by Django 5.2.1 on 2025-06-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubchatstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
